### ISSUE TITLE
oxCas should allow to skip CAS login page

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxCas#1]
We need to add option to WEB-INF/spring-configuration/applicationContext.xml to allow turn on automatic redirect to oxAuth login page. This should skip CAS login page.

**Comment by mzico** [comment]
@yurem: touching base.. any plan on this?

**Comment by yurem** [comment]
I think we need few hours to implement this. But I think it's low priority issue... Is it major issue?

**Comment by mzico** [comment]
@yurem : I have one client in my hand now who need that. I am okay with 'manual configuration' now if you prefer....

**Comment by yurem** [comment]
I prefer to resolve it once we will have some time...

**Comment by yurem** [comment]
Fixed. There is next option: https://github.com/GluuFederation/community-edition-setup/blob/master/templates/oxcas-config.json#L14 to control this.
